version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - 1323:80

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: databse
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306

volumes:
  db-data: