version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./.env:/.env
      - ./public:/public
    ports:
      - 1323:80

  # MySQL Support
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  # PostgreSQL Support
  # db:
  #   image: postgres:12.2-alpine
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     PGDATA: /data/postgres
  #   volumes:
  #     - db-data:/data/postgres
  #   ports:
  #     - 5432:5432

volumes:
  db-data: